title: Using CSC Environment Efficiently

plugins:
  - jekyll-sitemap

collections:
    lectures:
        output: true
    tutorials:
        output: true
    exercises:
        output: true
    extras:
        output: true

defaults:
  -
    scope:
      path: "_lectures"
    values:
      layout: "slides-csc"
  -
    scope:
      path: "_tutorials"
    values:
      layout: "default"
  -
    scope:
      path: "_exercises"
    values:
      layout: "default"
  -
    scope:
      path: "_extras"
    values:
      layout: "default"
